### PR TITLE
Description edit modified, but still error in patch request

### PR DESCRIPTION
**Pull request by nishantkr18**

### CODE REVIEW

**Comment by nishantkr18** [comment]
@mohit-mangal can u have a look at the patch request for description changing for clubs? I havent made it for council yet, because its showing the same old `Instance of <Response>` error.. Plz have a look..

**Comment by mohit-mangal** [comment]
> @mohit-mangal can u have a look at the patch request for description changing for clubs? I havent made it for council yet, because its showing the same old `Instance of <Response>` error.. Plz have a look..

Sorry for the inconvenience, it was a vulnerable yet unnoticeable  typo mistake in API request

**Comment by nishantkr18** [comment]
> Sorry for the inconvenience, it was a vulnerable yet unnoticeable typo mistake in API request

Oh, I too didnt notice that.. No worries :smiley:

**Comment by nishantkr18** [comment]
@mohit-mangal , description change for council were not completed.. have u done it?

**Comment by mohit-mangal** [comment]
> @mohit-mangal , description change for council were not completed.. have u done it?

what's left in it? :confused:

**Pull request merged**
