### PR TITLE
temp fix for workshop/{id}

### PR DESCRIPTION
**Pull request by nishantkr18**

### CODE REVIEW

**Comment by nishantkr18** [comment]
> I originally defined those as strings and later changed to double after looking at backend.
> Are you sure about Strings
> @nishantkr18

Its giving some serialization error for double, try opening the Arduino workshop with the double setting.. U'll know what I am talking about

**Comment by mohit-mangal** [comment]
> > I originally defined those as strings and later changed to double after looking at backend.
> > Are you sure about Strings
> > @nishantkr18
> 
> Its giving some serialization error for double, try opening the Arduino workshop with the double setting.. U'll know what I am talking about

ok let me check it once

**Comment by mohit-mangal** [comment]
ya , you were right

**Comment by nishantkr18** [comment]
> ya , you were right
> So, we will have to parse it into double in app

Yup, for now

**Pull request merged**
